# Site settings
title: Rmalkevy Blog
header-img: img/home-bg.jpg
email: henprokuror@gmail.com
description: "IT, programming, data science"
baseurl: ""
# url: "http://yourdomain.com"
github_username:  rmalkevy
facebook_username:  https://www.facebook.com/henprokuror

# Build settings
markdown: kramdown
highlighter: rouge #pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]

kramdown:
    input: GFM
    syntax_highlighter: rouge
